apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-app
  labels:
    app: aspnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-app
  template:
    metadata:
      labels:
        app: aspnet-app
    spec:
      containers:
        - name: aspnet-app
          image: webmasterdevlin/asp-weather-api-k8s:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-service
spec:
  selector:
    app: aspnet-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-redux-app
  labels:
    app: react-redux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-redux-app
  template:
    metadata:
      labels:
        app: react-redux-app
    spec:
      containers:
        - name: react-redux-app
          image: webmasterdevlin/redux-k8s:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "20m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-redux-service
spec:
  type: ClusterIP
  selector:
    app: react-redux-app

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt

spec:
  # frontend.<ingress ip>.nip.io
  tls:
    - hosts:
        - frontend.20.113.9.102.nip.io
      secretName: react-asp-cert
  rules:
    - host: frontend.20.113.9.102.nip.io
    - http:
        paths: # NodePort is not needed here
        - path: /
          pathType: Prefix
          backend:
            service:
              name: react-redux-service
              port:
                number: 8080
        - path: /weatherforecast
          pathType: Exact
          backend:
            service:
              name: aspnet-service
              port:
                number: 8081